FirestormViewer/phoenix-firestorm

- indra/llrender/CMakeLists.txt
I didn't like that fs-build-variables dragged in a -fPIC as CXXFLAGS because,
1) that is not how one should do that when using cmake (see this patch for how to do that).
2) that causes ALL files to be compiled with that flag, also normal viewer files that don't need it.
3) it isn't necessary for amd64.
Hence, I removed that flag locally.
Turns out this (one file of llrender) is the only thing that *does* need to be compiled with -fPIC (despite being on amd64) because [...].
So, added this line to make it so.
Needless to say that if you keep -fPIC in fs-build-variables anyway then this change has no effect,
but I'd appreciate it if it is accepted since it makes sense ;).
> llrender must be compiled with -fPIC.

- indra/newview/llenvironment.cpp
For the life of me I can't figure out which variable is supposedly undefined:
```
In file included from /usr/include/string.h:548,
from /usr/include/c++/13.2.1/cstring:42,
from /opt/secondlife/viewers/firestorm/phoenix-firestorm-git/indra/llcommon/linden_common.h:54,
from /opt/secondlife/viewers/firestorm/phoenix-firestorm-git/indra/newview/llviewerprecompiledheaders.h:38,
from /opt/secondlife/viewers/firestorm/phoenix-firestorm-git/indra/newview/llenvironment.cpp:27:
In function ‘void* memcpy(void*, const void*, size_t)’,
inlined from ‘void boost::function2<R, T1, T2>::move_assign(boost::function2<R, T1, T2>&) [with R = void; T0 = const LLUUID&; T1 = LLViewerRegion*]’ at /opt/secondlife/viewers/firestorm/phoenix-firestorm-git/build-linux-x86_64/packages/include/boost/function/function_tem …
```
> Compile warning/error workaround.

- indra/newview/llviewerwindow.cpp
<FS:Zi> missed this one.
Including this header leads to a linker error when compiling without optimization because then the LLPanelTopInfoBar constructor isn't inlined.
/usr/bin/ld: CMakeFiles/firestorm-bin.dir/llviewerwindow.cpp.o: in function `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > LLSingletonBase::classname<LLPanelTopInfoBar>()':
/opt/secondlife/viewers/firestorm/phoenix-firestorm-git/indra/llcommon/llsingleton.h:126:(.text._ZN15LLSingletonBase9classnameI17LLPanelTopInfoBarEENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEv[_ZN15LLSingletonBase9classnameI17LLPanelTopInfoBarEENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEv]+0x1e): undefined reference to `typeinfo for LLPanelTopInfoBar'
/usr/bin/ld: …
> Fix linker error.

- indra/media_plugins/cef/linux_volume_catcher.cpp
- indra/media_plugins/cef/linux_volume_catcher_pa_syms.inc
The volume slider for web media didn't seem to work for me. I'm using Pipewire which provides a Pulseaudio interface for other software to use and is fully compatible (through `/run/user/1000/pulse/native`). I took a look at the Linux volume catcher code and realized that `pa_mainloop_run` or `pa_mainloop_iterate` was never run.
In the official `pacat` (`paplay`) tool, they start the loop right after connecting with the newly created context:
https://github.com/pulseaudio/pulseaudio/blob/84f5b742e39ba3e375bac9144e0243b7331f4019/src/utils/pacat.c#L1222
Check out `pa_mainloop_iterate` here:
https://www.freedesktop.org/software/pulseaudio/doxygen/mainloop_8h.html#a491422aebe5487800d8be0bf4153cb81
I figured `pump()` was being called every 100 ms through `idle` message from …
> Fix Linux volume catcher

- indra/newview/fspanelface.cpp
This fixes the only build error I encountered trying to run `autobuild build -A 64 -c RelWithDebInfoFS_open`:
```
E:\cabbage\sl\phoenix-firestorm\indra\newview\fspanelface.cpp(1152,3): error C2065: 'comboTexGen': undeclared identifie r [E:\cabbage\sl\phoenix-firestorm\build-vc170-64\newview\firestorm-bin.vcxproj]
```
all the `getChild()` calls here are null-checked with an `if`, so I'm not sure why there's any llassert here
> fix RelWithDebInfo build error: 'comboTexGen': undeclared identifier

- indra/newview/llagentcamera.cpp
- indra/newview/llviewerregion.cpp
- indra/newview/llviewerregion.h
This PR addresses a regression introduced in recent Firestorm releases (7.1.3 and likely earlier) that prevents the camera from being positioned below Z=0 in OpenSim regions. This issue disrupts the ability of users to view avatars and objects situated at negative Z, hindering interaction with underwater builds and other scenarios. 
**Changes:**
- **Introduced `LLViewerRegion::mMinSimHeight` and `LLViewerRegion::getMinSimHeight()`** to track the minimum simulation height advertised by OpenSim regions. 
- **Refined the camera position calculation** in `llagentcamera.cpp` to respect `mMinSimHeight` when applicable, effectively removing the artificial Z=0 floor for OpenSim regions.
This solution leverages existing OpenSim infrastructure by using the `OpenSimExtras.MinSimHeight` value …
> FIRE-33613: Allow camera to view negative Z in OpenSim builds

- indra/newview/llagentbenefits.cpp
- indra/newview/llagentbenefits.h
- indra/newview/llfloatersnapshot.cpp
- indra/newview/llpanelsnapshot.cpp
- indra/newview/llpanelsnapshotinventory.cpp
- indra/newview/llpanelsnapshotoptions.cpp
- indra/newview/llsnapshotlivepreview.cpp
I don't know if there is a reason why snapshots to inventory have been blocked to 512x512 until now. If there are no reasons, then here is a pull request that allow to upload snapshots to inventory up to 2048x2048.
The cost of the upload is updated according to the area of the snapshot.
> Raised the 512x512 limitation for uploading snapshots to inventory to 2048x2048

- indra/llui/llfloaterreg.h
- indra/newview/llpathfindingnavmesh.cpp
- indra/newview/rlvcommon.cpp
- indra/newview/rlvhandler.cpp
Mostly errors like
```
phoenix-firestorm/indra/newview/fsfloaterimcontainer.cpp: In static member function ‘static void FSFloaterIMContainer::reloadEmptyFloaters()’:
phoenix-firestorm/indra/newview/fsfloaterimcontainer.cpp:433:42: error: possibly dangling reference to a temporary [-Werror=dangling-reference]
433 |     LLFloaterReg::const_instance_list_t& inst_list = LLFloaterReg::getFloaterList("fs_impanel");
|                                          ^~~~~~~~~
phoenix-firestorm/indra/newview/fsfloaterimcontainer.cpp:433:82: note: the temporary was destroyed at the end of the full expression ‘LLFloaterReg::getFloaterList(std::__cxx11::basic_string<char>(((const char*)"fs_impanel"), std::allocator<char>()))’
433 |     LLFloaterReg::const_instance_list_t& inst_list = …
```
> annotate gcc 13 dangling reference to temporary errors so they are ignored

- indra/newview/llfloateravatar.h
Override needed to make Clang not throw an error
> Make Clang Happier

- indra/newview/llvosurfacepatch.cpp
[[FIRE-34363] ](https://jira.firestormviewer.org/browse/FIRE-34363)
Fixes the problem and potential crash mentioned in the JIRA issue.
Edit: I have also put in a PR to the secondlife repo so this might be fixed by them directly soon-
https://github.com/secondlife/viewer/pull/2194
Edit2: Wow they are quick, they have already merged this change into the official secondlife repo.
> [FIRE-34363] Fixed unwanted implicit cast of U32 to U16 causing a crash

- indra/newview/app_settings/settings.xml
- indra/newview/gltfscenemanager.cpp
- indra/newview/llviewermenu.cpp
- indra/newview/llviewershadermgr.cpp
- indra/newview/skins/default/xui/en/notifications.xml
Backport fixes for secondlife/viewer#1856
Add error handling for intel crashes from GLTF Scene shader (secondlife/viewer#2456)
more details can be found in secondlife/viewer#1856, but systems based on Intel integrated HD 4000 series and 5000 series GPU would crash on startup before reaching the login screen
> Backport fix for secondlife/viewer#1856

- indra/newview/app_settings/key_bindings.xml
- indra/newview/llkeyconflict.cpp
- indra/newview/llviewerinput.cpp
- indra/newview/skins/default/xui/en/control_table_contents_camera.xml
Adds key bindings for the new Camera Roll feature that got accepted a few weeks ago. I think this will make the camera roll feature more useful for people who use keyboard shortcuts to control the camera.
By default, I chose the following keys:
- R (roll left)
- T (roll right)
I couldn't find any other use for these keys so I think it's alright without any modifier, and also convenient. Easy to remember as R is for Roll.
You might have to define the keys yourself or reset key bindings to defaults after an update for this to work, at least I had to do it on my computer.
You can see the new key bindings in Preferences > Controls > When in third person or When sitting, under the Camera section.
> Add key bindings for Camera Roll

- indra/newview/fspanellogin.cpp
- indra/newview/fspanellogin.h
- indra/newview/skins/default/xui/en/panel_fs_login.xml
- indra/newview/skins/default/xui/en/panel_fs_nui_login.xml
Add an "eye" button on the login screens allowing visible password text
See https://jira.firestormviewer.org/browse/FIRE-34629 for what this looks like.
This re-uses an existing "eye" button graphic from group permissions.   To be perfectly neat and clean, either this feature should have it's own button graphics, or the existing ones should be renamed to be something more generic.  That said, it works and has minimal disruption of other code and doesn't add more files and data to the download.   It didn't seem worth the effort.
I did not touch the Linden login files since I assume that would be better left alone and might do a patch for that viewer someday
> FIRE-34629 Add an "eye" button on the login screen allowing visible password text

- indra/newview/ao.cpp
- indra/newview/ao.h
> If user clicks on up/down buttons from AO UI to change animation order in the list then clicks on the next/previous animation buttons that will bold/highlight the wrong current playing animation in the AO UI list.
> 
> Here are the steps to reproduce:
> 
> Create a new AO set then drag and drop at least 2 animations, then click on the up/down buttons to change its order in the list then click on the next/previous buttons to change animations, you will notice the bold/highlighted animation is not actually the one being played by the avatar.
That happens because the scroll list item userdata is only updated during `FloaterAO::onSelectState` so when clicking on up/down(`FloaterAO::onClickMoveUp()`/`FloaterAO::onClickMoveDown()`) buttons, every `LLScrollListItem` is not being updated with …
> [FIRE-35037] AO UI scroll list bold/highlight fix.

- indra/llui/llconsole.cpp
- indra/newview/app_settings/commands.xml
- indra/newview/app_settings/settings.xml
- indra/newview/llviewermenu.cpp
- indra/newview/skins/default/xui/en/menu_viewer.xml
- indra/newview/skins/default/xui/en/panel_preferences_chat.xml
Issue:
When using DFS, especially cooking, the on-screen console window tends to cover much of the screen, including HUD objects like the DFS interface or objects that the user is interacting with like recipes, etc. It would be nice to be able to hide the on-screen console window, especially easily with say a key combo and/or an on screen button. This way the user could hide it while performing actions then turn it back on when playing normal or interacting with others.
Example of the issue of the on-screen console covering HUB UI elements and interactive objects in the world.
Proposed solution:
Add a new persist boolean in the settings.xml file for tracking if the on-screen console should draw and have three ways to change the value:
1. Checkbox in the Preferences->Chat->Visuals labelled …
> [FIRE-35039] Add flag to show/hide the on-screen console

- indra/newview/app_settings/settings.xml
- indra/newview/llhudobject.cpp
- indra/newview/llhudobject.h
- indra/newview/llhudtext.cpp
- indra/newview/llhudtext.h
- indra/newview/lltoolpie.cpp
- indra/newview/llviewerobject.cpp
- indra/newview/llviewerobject.h
- indra/newview/skins/default/xui/en/panel_preferences_UI.xml
- indra/newview/skins/default/xui/en/panel_preferences_colors.xml
This pull is to add support for in world floating text to have a background based on the LLHUBNameTag object. This also adds support for when a prim which has a floating text is hovered over. The text becomes opaque and changes its render order to appear over all other floating text, as well as the background pulled forward. This also disables the floating text fade on the highlighted text so that very far away objects can be checked.
This is designed support better contrast the text from other floating text that may be near. I play DFS with my wife and there tends to be a lot of floating text. With my color blindness I had a hard time reading some of the darker text as well as seeing what item I am hovering over.
This is an example of what the our sim looks like currently with no …
> [Fire-35019] Add LLHUDNameTag background to floating text and hover highlights

- indra/newview/llhudtext.cpp
- indra/newview/llhudtext.h
I have reverted the changes to the LLHUDText to the original calculations for the line spacing and width.
The background now uses its own width based upon the actual text width. The LLHUDText is using a max with of 190 pixels for the object, but the text can go beyond this. I originally used the actual width of the object, but modified it to correct for the error. Now I just interpedently calculate the width of the object and actual text. They were originally updated to match the LLHUDNameTag as it seemed to be more modernized and they are based on the same code originally.
Below is a demonstration showing that the fonts match with the older releases.
7.1.11 Release
Fixed version
I used the code from before my changes to make sure the un-done code matches the original formatting.
> FIRE-35078 - llSetText(...) differences in latest Nightly Builds

- indra/newview/skins/starlight/xui/en/panel_main_inventory.xml
Needed to add 32 pixels to the dumm_panel lef_pad to make room for the new filter button. 
Minor fix.
Issue:
Fixed:
> FIRE-35074 - XML Issue with updated starlight skin main inventory - dummy_panel

- indra/newview/linux_tools/wrapper.sh
This change fixes the IME to work even if the desktop environment is running on Wayland.
Thank you for contributing to the Phoenix Firestorm Project.
We will endeavour to review you changes and accept/reject/request changes as soon as possible. 
Please read and follow the [Firestorm Pull Request Guidelines](https://github.com/firestormviewer/phoenix-firestorm/blob/master/FS_PR_GUIDELINES.md) to reduce the likelihood that we need to ask for "Bureaucratic" changes to make the code comply with our workflows.
> enable ime on xwayland

- indra/newview/llinventoryfilter.cpp
- indra/newview/llpanelmaininventory.cpp
- indra/newview/skins/ansastorm/xui/en/panel_main_inventory.xml
- indra/newview/skins/default/xui/en/panel_main_inventory.xml
- indra/newview/skins/default/xui/en/strings.xml
- indra/newview/skins/starlight/xui/en/panel_main_inventory.xml
- indra/newview/skins/starlightcui/xui/en/panel_main_inventory.xml
- indra/newview/skins/vintage/xui/en/panel_main_inventory.xml
This lets you limit your search to folders only. Very useful when you have a large inventory and you need to find a specific folder without the search getting drown with folder items.
It does not change the default behavior, if you uncheck "Include items" it will limit the search to folders only and show only folders.
Normal behavior, "Include items" checked
"Include items" unchecked
> Allows to limit search to folders only in inventory

- indra/llui/lltexteditor.cpp
- indra/llui/lltexteditor.h
- indra/newview/llpanelprofile.cpp
- indra/newview/llpanelprofile.h
- indra/newview/llpanelprofilepicks.cpp
- indra/newview/llpanelprofilepicks.h
- indra/newview/skins/default/xui/en/panel_profile_firstlife.xml
- indra/newview/skins/default/xui/en/panel_profile_pick.xml
- indra/newview/skins/default/xui/en/panel_profile_secondlife.xml
Added preview buttons in profile panel to preview the About section, Picks and First Life introduction like others would see it, very useful to preview links with custom label for example.
I added the reparseValue and reparseText methods in LLTextEditor so that it doesn't remove the dirty state and undos when switching between edit mode and preview mode.
Here's what it looks like:
**About section:**
**Picks:**
**First Life:**
> Added preview buttons in profile panel

- indra/newview/llpanelprofile.cpp
- indra/newview/llpanelprofilepicks.cpp
This disables rendering links when a pick or 1st life texts are in edit mode (white background, only for own profile).
It makes the preview feature work as intended.
This actually had nothing to do with the preview feature, but it allowed to notice that old bug more easily.
> [FIRE-35185] Profile preview removing embedded URLs from 1st Life tab

- indra/llwindow/llwindowcallbacks.cpp
- indra/llwindow/llwindowcallbacks.h
- indra/llwindow/llwindowwin32.cpp
- indra/newview/llviewerwindow.cpp
- indra/newview/llviewerwindow.h
Hey people,
First contrib so please be patient! 
I have fixed:
[FIRE-10419] (Reported in 2013)
https://jira.firestormviewer.org/browse/FIRE-10419
and
[FIRE-32546]
https://jira.firestormviewer.org/browse/FIRE-32546 which is a dupe.
So the problem is that some devices and applications will cause windows to send out device notifications frequently, this causes a 10-15 second stutter whenever this happens, this can be every few minutes. 
So what i've done is basically register for device notifications, then filter out what we need based on CLSIDs to only init those, 
This based on https://jira.firestormviewer.org/secure/attachment/22091/joystick2.patch by Casper Warden but with a bunch of changes. For one I dropped the sensors for now as we don't need them, cleaned up the code a little and …
> [FIRE-10419] Selectively process devices based on CLSID to prevent stuttering

- indra/newview/pipeline.cpp
Detailed description of the changes.
This Pull Request addresses an issue where Screen Space Ambient Occlusion (SSAO) appearance was inconsistent, particularly in high-resolution snapshots compared to the main viewer window.
**This fix is based on a similar method previously implemented by BeqJanus to address the same type of resolution inconsistency issue with Depth of Field effects in snapshots.**
Previously, the SSAO radii parameters (RenderSSAOScale and RenderSSAOMaxScale) were directly applied to the shader without considering the resolution difference between the viewer window and the render target (snapshot).  This resulted in SSAO appearing too small and under-sampled in high-resolution snapshots, as the sampling radius was not scaled up to match the larger snapshot resolution.
To …
> Fixes: Improve SSAO Appearance Consistency for High-Resolution Snapshots

- indra/newview/llurllineeditorctrl.cpp
This fixes [FIRE-34020](https://jira.firestormviewer.org/browse/FIRE-34020) by ensuring that `hop://` addresses are correctly URL-encoded when copied to the clipboard from the address bar, similar to `secondlife://` addresses.
The problem was that `LLURLLineEditor::copyEscapedURLToClipboard` only knew about `http://` and `secondlife://` schemes. With this change it now handles `hop://` as well.
Testing:
1. Visit any OpenSim region containing spaces (for example) in the Region Name.
2. Copy the address bar to the clipboard (using <kbd>ctrl-c</kbd> or context menu).
3. Paste the clipboard contents somewhere and should see `%20`'s have been applied.
Thanks!
cc: @aiaustin
> [FIRE-34020] [OPENSIM] Copy of address bar contents does not URL encode space in region name for OpenSim only

- indra/newview/llagentbenefits.cpp
[[FIRE-35276]](https://jira.firestormviewer.org/browse/FIRE-35276)
Fix for client freeze in OpenSim getting picks limit.
Setting the max picks limit to S32_MAX for OpenSim from my limited testing appears to have 0 downside and older viewers still handle this fine, they just don't allow additional picks to be created past 10.
If you believe using S32_MAX is excessive and it should be hard capped to a more reasonable number (such as 20 like on official secondlife which is set by their servers and told to the viewer), let me know and I'll update the PR accordingly.
> [FIRE-35276] Fix for client freeze in OpenSim getting picks limit

- indra/newview/llpanelprofile.cpp
[FIRE-35304](https://jira.firestormviewer.org/browse/FIRE-35304)
Fixes not being able to view and edit your own profiles notes while in OpenSim.
This is achieved by removing the incorrectly added !getSelfProfile() check. I also removed the redundant additional gAgent.getRegionCapability(PROFILE_PROPERTIES_CAP).empty() check since it already does it.
> [FIRE-35304] Fix viewing and editing your own profile notes in OpenSim

- indra/newview/llnetmap.cpp
[FIRE-35147](https://jira.firestormviewer.org/browse/FIRE-35147)
Fixes two issues with the MiniMap when playing in OpenSim-
1. If a region is greater than 256x256, it now correctly renders the entire region on the MiniMap instead of only only rendering the first 256x256 potion.
2. When you change to a new grid, it now correctly renders on the MiniMap the regions you spawned in, instead of it being incorrectly rendered until you left and came back.
> [FIRE-35147] OpenSim MiniMap rendering fixes

- indra/newview/daeexport.cpp
- indra/newview/fsfloaterexport.cpp
- indra/newview/llagentbenefits.cpp
[FIRE-35292](https://jira.firestormviewer.org/browse/FIRE-35292)
Fixes the issue described in the Jira ticket where exporting textures as PNG or TGA were getting downscaled and compressed when they weren't supposed to be. This is achieved by simply setting the discard level back to 0 before it decodes the image and saves it to disk.
_Fixing the Uploading of J2C textures is not implemented yet. This is an issue that impacts secondlife's viewer too, and as such, I have opened an issue with their version and they have already taken it on as a bug and slated for milestone 2025.04. If LL chooses not to fix it themselves, or their fix needs changes for OpenSim, I will open another PR when necessary_
(Also corrects a minor error in a comment from a previous commit)
> [FIRE-35292] Fix Exporting Texture getting downscaled and compression

- indra/newview/app_settings/settings.xml
- indra/newview/llvieweraudio.cpp
[FIRE-35317](https://jira.firestormviewer.org/browse/FIRE-35317)
LindenLabs a while ago removed the AudioLevelWind debug setting since they considered it "unused". 
This PR simply reverts this change and brings it back, since there are some users who wish to disable to wind sound when hovering still.
> [FIRE-35317] Restore AudioLevelWind as a debug setting

- indra/newview/skins/default/xui/en/floater_region_info.xml
- indra/newview/skins/default/xui/en/panel_region_access.xml
- indra/newview/skins/default/xui/en/panel_region_terrain.xml
[FIRE-35331](https://jira.firestormviewer.org/browse/FIRE-35331)
Currently, the Region/Estate floater is sized too small so that the terrain tab is missing the Apply button. It is also missing some of the PBR Transforms settings due to getting cut off.
This PR resizes the the float and individual panels so everything is accessible again, and it also readjusts the Access panel so there isn't unused space.
> [FIRE-35331] Fix Region/Estate panel sizes

- indra/llcommon/llstring.cpp
Based on FIRE-34775, switching back to PST/PDT for the OpenSim version, retaining SLT at SL. I don't have a test environment, but this probably works.
> FIRE-34775: For OpenSim switch back to PST/PDT

- indra/llui/llurlentry.cpp
- indra/newview/llfloaterworldmap.cpp
- indra/newview/llfloaterworldmap.h
- indra/newview/lltracker.cpp
Fixes all problems in the two following Jira issues-
https://jira.firestormviewer.org/browse/FIRE-35268
https://jira.firestormviewer.org/browse/FIRE-35333
1. Copying the SLurl on the world map in OpenSim, now correctly creates the SLurl of the grid you are on (you will need to wait a few seconds on a new grid, since the viewer doesn't receive the latest grids simulation features and grid info until a few seconds after arriving. Attempting to immediately copy the SLurl on a new grid will still have the old grid url. There is no  easy way around this without fixing the overarching race condition issue on grid swapping)
2. Hop protocol urls in nearby chat and IM's now get correctly hyperlinked if the coordinates are missing, or if the Z value in the coordinate is negative (supported by …
> Hop protocol fixes and negative Z coordinate OpenSim support

- scripts/configure_firestorm.sh
This is just a small change to the configuration script. Previously, tee would interpret build paths containing spaces as two separate arguments. Wrapping the build path in quotes prevents this.
> Fix build logging when the build path contains spaces

- indra/newview/fspanelface.cpp
- indra/newview/fspanelface.h
- indra/newview/llface.cpp
- indra/newview/llselectmgr.cpp
- indra/newview/llselectmgr.h
- indra/newview/llviewerobject.cpp
- indra/newview/llviewerobject.h
- indra/newview/llvovolume.cpp
[FIRE-32413](https://jira.firestormviewer.org/browse/FIRE-32413)
[FIRE-34261](https://jira.firestormviewer.org/browse/FIRE-34261)
[FIRE-34350](https://jira.firestormviewer.org/browse/FIRE-34350)
[FIRE-35138](https://jira.firestormviewer.org/browse/FIRE-35138)
[FIRE-35173](https://jira.firestormviewer.org/browse/FIRE-35173)
While using the legacy LL texture panel instead of the FS alternative one, attempting to edit GLTF settings will cause textures on the material to be reverted/removed.
This was caused by the LLRenderMaterialOverrideFunctor intended for the FS texture panel to be used for the regular one, which resulted in it not applying settings properly. This PR simply renames the functor so it is only used for the FS texture panel and not the LL texture panel.
Additionally, when …
> Fix GLTF texture panel bugs and inconsistencies compared to SLViewer

- indra/llui/llurlentry.cpp
[FIRE-35381](https://jira.firestormviewer.org/browse/FIRE-35381)
Fixes the LLUrlEntryPlace regex pattern by and ensuring both hop:// and secondlife:// urls only apply to those which are meant for locations.
> [FIRE-35381] Fixes experience and item urls showing as raw urls

- indra/newview/llviewerwindow.cpp
In the current implementation, clicking objects in mouselook (first-person) mode does not function correctly because the viewer attempts to pick using the hidden mouse cursor location instead of the center of the screen where the crosshair is located. This leads to objects being unclickable, significantly impairing the usability of mouselook mode.
This pull request fixes the issue by adjusting the picking logic within `LLViewerWindow::pickImmediate()` to always use the center coordinates of the viewport when in mouselook mode.
Modified `indra/newview/llviewerwindow.cpp`:
```cpp
// <FS:Sek> Pick from center of screen in mouselook
if (gAgentCamera.getCameraMode() == CAMERA_MODE_MOUSELOOK)
{
x = gViewerWindow->getWorldViewRectScaled().getWidth() / 2;
y_from_bot = …
```
> Fix object and HUD clicking in mouselook mode

- indra/newview/llfloaterimnearbychathandler.cpp
The feature that minerjr added with FIRE-35039 covered the vintage style console chat, and added the checkbox corner on the chat toolbar icon. It bothered me that this feature didn't work for toast chat since that's my preferred method, so I am providing my implementation that covers this case.
> [FIRE-35294] Make minerjr's chat console hiding work with toast chat too

- indra/newview/app_settings/graphic_preset_controls.xml
- indra/newview/llpresetsmanager.cpp
[FIRE-35390](https://jira.firestormviewer.org/browse/FIRE-35390)
When loading a graphical preset from 7.1.11 or earlier, unless the user had explicitly set RenderSkyAutoAdjustLegacy to false and RenderSkyAmbientScale to 1.0 in debug settings before creating the preset, these debug settings are set as true and 0.7 respectively and get loaded into newer viewers and remains true and 0.7 unless a user manually turns them back to their default values in debug settings.
Setting graphical settings to default does not set this value back to false either (which I believe is intentional so I didn't change this). However, if the users "Default.xml" preset was automatically created on 7.1.11 or earlier, loading that to try and default your settings also sets RenderSkyAutoAdjustLegacy to true and …
> [FIRE-35390] Fix loading old presets with RenderSkyAutoAdjustLegacy and RenderSkyAmbientScale causing graphical inconsistency

- indra/newview/llappviewerwin32.cpp
- indra/newview/llappviewerwin32.h
[FIRE-34791](https://jira.firestormviewer.org/browse/FIRE-34791)
Possible fix for FullScreen not working on specific Windows setups based on Rilene Starlights information-
https://jira.firestormviewer.org/browse/FIRE-34791?focusedId=246285&#comment-246285
As well as additional information I discovered here-
https://jira.firestormviewer.org/browse/FIRE-34791?focusedId=246321&#comment-246321
This might not fix the issue as a whole, but it should fix the specific issue relating to what Rilene described which I do believe to be the same issue based on information I found.
Duplicate of my changes that got merged into SLV-
https://github.com/secondlife/viewer/pull/4023
> [FIRE-34791] Fix FullScreen failing on Windows 11 24H2

- indra/newview/aoengine.cpp
This fixes a potential crash in the AO panel.
If an animation does not exist in inventory but exists in the AO panel, it would crash.
This is probably the cause of FIRE-35293
It will now silently exit from the AOEngine::playAnimation method if the animation does not exist in inventory.
> fix potential crash if item doesn't exist in inventory (potentially fixes FIRE-35293)

- indra/newview/ao.cpp
- indra/newview/aoengine.cpp
This is my second attempt at fixing FIRE-35293.
I added more nullptr checks and safer casts in AOEngine::playAnimation and FloaterAO::onAnimationChanged methods.
Hopefully it will not crash anymore. I couldn't make it crash even after deleting for good some animations in my AO set and double-clicking on them.
> fix potential crashes in AO panel when double-clicking (should fix FIRE-35293)

- indra/newview/llviewermessage.cpp
This PR adds support for reporting canceled restarts so that scripts users write to avoid them by way of scripted teleports won't be teleported away thinking the restart is still on track.
I spoke with Pantera about the best way to implement this, and exchanged thoughts with Lucia Nightfire who holds the only known public implementation of this feature that Pantera or I are aware of. My original intention was to send a -1 value to the chat message however it was understood that this would break Lucia's existing scripted item on the marketplace.
- Link to the product: https://marketplace.secondlife.com/p/Box-Region-Restart-Evader-HUD-Updated-April-8-2022/23463179
The settled-upon best course forward after speaking with both parties was for a different message entirely to be sent, which …
> Add support for canceled restarts to region restart channel reporting

- indra/newview/skins/starlightcui/xui/en/sidepanel_task_info.xml
This PR adjusts the title over the object profile popup on the Starlight CUI skin. This was reported in the Firestorm Support English chat by Vulcan Viper.
> Bugfix: Correct floater XUI title overrun on Starlight CUI object profile view

- indra/newview/skins/starlight/xui/en/floater_tools.xml
- indra/newview/skins/starlightcui/xui/en/floater_tools.xml
- indra/newview/skins/vintage/xui/en/floater_tools.xml
[FIRE-35529](https://jira.firestormviewer.org/browse/FIRE-35529)
Fixes the above issue
> [FIRE-35529] Add missing filters on object inventories for Starlight and Vintage skins

- indra/newview/app_settings/graphic_preset_controls.xml
Follow up to this-
https://github.com/FirestormViewer/phoenix-firestorm/pull/114
Reverting the changes of removing RenderSkyAmbientScale and RenderSkyAutoAdjustLegacy from the graphic_preset_controls.xml, but still leaving them being defaulted for now.
The reason being is, when LL eventually bump their featuretable version number, we want these settings to be defaulted by that forced reset (due to the problem discussed in the above PR and the issue it links).
Also, after the bump to the version, we can then remove the need for defaulting the value on preset load and instead change it to just not load the setting from presets, even though it is still being saved and resettable.
This way we solve- 1. The bump fixes incorrect settings being kept after a preset load of an old preset without …
> Revert on removing RenderSkyAmbientScale and RenderSkyAutoAdjustLegacy from graphic_preset_controls.xml

- indra/newview/llteleporthistory.cpp
- indra/newview/llteleporthistory.h
[FIRE-35355](https://jira.firestormviewer.org/browse/FIRE-35355)
Fixes problem 2 listed in the above issue.
Ever since the existence of the navigation bar, while you are hypergridding in OpenSim, if you try and use the back or forward buttons to return to a different grid than the one you are on, it would simply just fail and error saying it couldn't teleport.
This PR makes it so the navigation bars teleport history stores the slurl of the current region whenever you teleport, then when you initiate a teleport with the back or forward button, if it is a different grid it requests the global position from the server using the stored slurl and teleports to the location on the grid that way (since the global position is dependent on what grid you are on).
> [FIRE-35355] Fixes navigation bar back and forward buttons while hypergridding in OpenSim

- indra/newview/fsfloaterim.cpp
- indra/newview/llimview.cpp
This was an annoying bug! It should be fixed with that PR.
**Summary**
This patch resolves an issue where the viewer incorrectly reused an existing session with the wrong dialog type (e.g., treating a group chat as a one-on-one IM). This led to confusing behavior when opening IMs with users who had previously initiated a group conversation.
**Changes**
_llimview.cpp:_
- Added type-checking logic to LLIMMgr::addSession() to ensure sessions are reused only if their mType matches the requested dialog.
- If a session exists but has a mismatched type, a new session is created instead.
- Used computeSessionID() for deterministic session creation where appropriate; generated a random UUID for conference sessions.
- Logged mismatches with LL_WARNS for debug visibility.
_fsfloaterim.cpp:_
- …
> [FIRE-34494] fixes unable to open an IM with someone who started a group chat

- indra/newview/fsareasearch.cpp
- indra/newview/fsareasearch.h
- indra/newview/skins/default/xui/en/floater_fs_area_search.xml
This PR adds support to area search for filtering reflection probe objects. The most reliable way I was able to get objects to show be detected was checking for a object coupled to the object, but am open to suggestions for a method that may work better across all circumstances.
> Add support to area search for filtering reflection probes

- indra/newview/fsfloaterprimfeed.cpp
(I'm an idiot and closed the previous PR by mistake while updating my fork. I'm re-opening it using a feature branch to avoid doing that again.)
Original PR: https://github.com/FirestormViewer/phoenix-firestorm/pull/133
https://github.com/FirestormViewer/phoenix-firestorm/commit/51c461500dabd9014786b695e9f29f7ed96edab7 introduced the use of `constexpr` with a `std::string`. This is C++20 compliant but not supported by gcc-11, which is our target compiler for Linux.
As a result, Linux users are currently unable to build Firestorm without a patch.
While we could replace the string with a stringview, LLSD params (just a few lines down) will complain because it expects a string, so more refactoring would be required.
Reverting from `constexpr` back to `static const` is the simplest and least …
> primfeed: cannot use string with constexpr; revert to static const

- indra/newview/app_settings/settings.xml
- indra/newview/llviewermenu.cpp
- indra/newview/skins/default/xui/en/panel_preferences_firestorm.xml
This PR adds a setting to simplify toggling between menu presets (e.g. ctrl+shift+Y for midday) and shared environment. When the setting is true and the requested preset is already active, it overrides the request to shared settings.
Setting is disabled by default.
https://github.com/user-attachments/assets/6184bddf-e4d3-4197-9156-3b2cfc06d3ad
> Option to short-circuit repeated environment keybinds to shared environment

- indra/newview/llselectmgr.cpp
[FIRE-34257](https://jira.firestormviewer.org/browse/FIRE-34257)
Fixes the above issue by moving the code dealing with Select only Copyable and Select only Locked objects inside the "!ignore_select_owned" block, which only fires when selecting an object in build/edit mode. When just mousing over and clicking on objects without build/edit mode up, ignore_select_owned is true and therefore is won't prevent the object from still being clicked with either of the 2 above settings enabled.
This behaviour makes those options behave like both SelectOwnedOnly and SelectMovableOnly already did.
> [FIRE-34257] Fix mousing over and clicking objects with FSSelectCopyableOnly or FSSelectLockedOnly enabled

- indra/llui/lltextbase.cpp
- indra/newview/skins/default/xui/en/panel_preferences_colors.xml
As requested by Anastasia and Beq, this change makes it so when searching for something in preferences, it sets the font colour of items found in the actual pages, and not just the tab and menu buttons.
Note: This is different from LL's behaviour, they always just use "LabelTextColor" even when things are highlighted.
Also fixes a slight misalignment of the area search beacon colour picker.
> Set the font color of search highlighted text

- indra/newview/llviewermenu.cpp
This pull request simply adds the object's PBR textures to the `faces_per_texture` list that eventually gets discarded and redownloaded. Change is wholly contained within Zi's original 'FS' tags for the Texture Refresh feature, so I haven't added any more.
> Include PBR textures in Texture Refresh.

- indra/newview/app_settings/settings.xml
- indra/newview/llviewerdisplay.cpp
- indra/newview/skins/default/xui/en/menu_viewer.xml
- indra/newview/skins/default/xui/en/panel_preferences_graphics1.xml
Disables the Draw Distance VRAM optimization that LL implemented to be on by default, that way when your VRAM gets very low, the draw distance doesn't plummet for seemingly no reason and people have reported it believing it to be a bug.
Added a toggle under Preferences->Graphics->Renderer to turn this optimisation back on
Also added the toggle to the Developer->Rendering menu
> [FIRE-35748] Disable Draw Distance VRAM Optimization and add it as a toggle

- indra/newview/llinventoryfunctions.cpp
- indra/newview/llinventoryfunctions.h
- indra/newview/llwearableitemslist.cpp
- indra/newview/skins/default/xui/en/menu_wearable_list_item.xml
This adds a context menu entry when right clicking on an item in an outfit, in the Appearance window, Outfits tab.
This is useful for when you mistakenly added some HUD or anything else you didn't want in your outfit.
This is simpler than going inside the inventory and deleting the links from the outfit folder.
This only deletes the links of course, not the real inventory item.
There is currently no confirmation, it deletes the links right away.
> Add 'Delete from outfit' context menu entry
